FROM rockylinux:8.5

# install python and other libs
RUN dnf install -y python3.9 nano tree gcc python39-devel

# do python libs and salt installation
RUN python3 -m pip install pip setuptools wheel poetry --upgrade 
RUN python3 -m pip install salt pytest 

# create user and install libs for salt-api
RUN useradd -m saltuser && usermod -g root saltuser
RUN python3 -m pip install cherrypy==18.8.0 

# run Salt Nornir libs installation from local files 
COPY salt_nornir/ /tmp/salt_nornir/
COPY nornir_salt/ /tmp/nornir_salt/
RUN python3 -m pip install /tmp/nornir_salt/.[prodmin] --upgrade 
RUN python3 -m pip install /tmp/salt_nornir/.[prodmin] --upgrade 
RUN python3 -m pip install N2G 

# start salt-master and salt-api
COPY salt_nornir/test/master_start.sh /tmp/master_start.sh
RUN chmod 775 /tmp/master_start.sh
CMD /tmp/master_start.sh