FROM centos:7

RUN yum install -y python3 nano
RUN python3 -m pip install pip --upgrade
RUN rpm --import https://repo.saltproject.io/py3/redhat/7/x86_64/latest/SALTSTACK-GPG-KEY.pub
RUN curl -fsSL https://repo.saltproject.io/py3/redhat/7/x86_64/3002.repo | tee /etc/yum.repos.d/salt.repo
RUN yum install -y salt-minion
RUN python3 -m pip install ipdb

ADD . /tmp/salt_nornir/
COPY test/proxy /etc/salt/proxy

# do misc libs installation
RUN python3 -m pip install -U pip setuptools 
RUN python3 -m pip install ttp
RUN python3 -m pip install xmltodict
RUN python3 -m pip install tabulate

# install SALT nornir libs from local volume
RUN python3 -m pip install /tmp/salt_nornir/ --ignore-installed PyYAML

# must run nornir_salt installation from local files one more time
# as salt_nornir pulls older version of nornir_salt from PyPi during installation
RUN python3 -m pip install /tmp/salt_nornir/nornir_salt

# Install scrapli and dependencies. It needs ntc-template<2.0.0,>=1.1.0,
# below is to make sure this is the case
RUN python3 -m pip uninstall -y ntc-templates
RUN python3 -m pip install ntc-templates==1.7.0
RUN python3 -m pip install nornir_scrapli
RUN yum install -y openssh-server openssh-clients

ENTRYPOINT ["salt-proxy", "--proxyid=nrp1", "-l", "debug"]