FROM centos:7

# install misc libs
RUN yum install -y python3 nano tree

# install SaltStack
RUN rpm --import https://repo.saltproject.io/py3/redhat/7/x86_64/latest/SALTSTACK-GPG-KEY.pub
RUN curl -fsSL https://repo.saltproject.io/py3/redhat/7/x86_64/3004.repo | tee /etc/yum.repos.d/salt.repo
RUN yum install -y salt-master

COPY salt_nornir/ /tmp/salt_nornir/
COPY nornir_salt/ /tmp/nornir_salt/
COPY salt_nornir/test/requirements.master.txt /tmp/requirements.txt

# do python libs installation
RUN python3 -m pip install pip setuptools --upgrade
RUN python3 -m pip install -r /tmp/requirements.txt

# run Salt Nornir libs installation from local files 
RUN python3 -m pip install /tmp/nornir_salt/ --upgrade
RUN python3 -m pip install /tmp/salt_nornir/ --ignore-installed PyYAML --upgrade

ENTRYPOINT ["salt-master", "-l", "debug"]