FROM centos:7

# install misc libs
RUN yum install -y python3 nano tree
RUN yum install -y openssh-server openssh-clients

# install SaltStack
RUN rpm --import https://repo.saltproject.io/py3/redhat/7/x86_64/latest/SALTSTACK-GPG-KEY.pub
RUN curl -fsSL https://repo.saltproject.io/py3/redhat/7/x86_64/3002.repo | tee /etc/yum.repos.d/salt.repo
RUN yum install -y salt-minion

COPY . /tmp/salt_nornir/
COPY test/proxy /etc/salt/proxy
COPY test/requirements.minion.txt /tmp/requirements.txt

# do python libs installation
RUN python3 -m pip install pip setuptools --upgrade
RUN python3 -m pip install -r /tmp/requirements.txt --ignore-installed PyYAML

# run Salt Nornir libs installation from local files 
RUN python3 -m pip install /tmp/salt_nornir/nornir_salt
RUN python3 -m pip install /tmp/salt_nornir/

ENTRYPOINT ["salt-proxy", "--proxyid=nrp1", "-l", "debug"]