FROM python:3.9-slim-bullseye

COPY salt_nornir/test/master_start.sh /tmp/master_start.sh

RUN apt-get update && \
    apt-get install --no-install-recommends -y openssh-client openssh-server gcc g++ autoconf make libffi-dev libssl-dev && \
    apt-get clean && \
    pip install --no-cache-dir pip setuptools wheel poetry pytest --upgrade && \
    useradd -m saltuser && \
    usermod -g root saltuser && \ 
    chmod 775 /tmp/master_start.sh

RUN apt-get install --no-install-recommends -y gdb python3.9-dbg

COPY salt_nornir/ /tmp/salt_nornir/
COPY nornir_salt/ /tmp/nornir_salt/

RUN pip install --no-cache-dir /tmp/nornir_salt/.[prodmaxmaster] --upgrade && \
    pip install --no-cache-dir /tmp/salt_nornir/.[prodmaxmaster] --upgrade

RUN USE_STATIC_REQUIREMENTS=1 pip install --no-cache-dir salt==3006

CMD /tmp/master_start.sh
# CMD salt-master -l debug