FROM python:3.9.7-slim-bullseye

ADD salt_nornir/test/saltinit.py /usr/local/bin/saltinit

COPY salt_nornir/test/ssh_config.txt /root/.ssh/config

RUN apt-get update && \
    apt-get install --no-install-recommends -y openssh-client openssh-server gcc g++ autoconf make libffi-dev libssl-dev dumb-init && \
    apt-get clean && \
    pip install --no-cache-dir pip setuptools wheel poetry pytest --upgrade && \
    useradd -m saltuser && \
    usermod -g root saltuser && \
    chmod 775 /usr/bin/dumb-init && \
    chmod 775 /usr/local/bin/saltinit && \
    chmod 644 /root/.ssh/config

COPY salt_nornir/ /tmp/salt_nornir/
COPY nornir_salt/ /tmp/nornir_salt/

RUN pip install --no-cache-dir /tmp/nornir_salt/.[prodmaxmaster] --upgrade && \
    pip install --no-cache-dir /tmp/salt_nornir/.[prodmaxmaster] --upgrade && \
    pip install --no-cache-dir /tmp/nornir_salt/.[prodmaxminion] --upgrade && \
    pip install --no-cache-dir /tmp/salt_nornir/.[prodmaxminion] --upgrade
    
RUN USE_STATIC_REQUIREMENTS=1 pip install --no-cache-dir salt==3006.5

ENTRYPOINT ["/usr/bin/dumb-init"]
CMD ["/usr/local/bin/saltinit"]