FROM centos:7

# install misc libs
RUN yum install -y python3 nano tree

# install SaltStack
RUN rpm --import https://repo.saltproject.io/py3/redhat/7/x86_64/latest/SALTSTACK-GPG-KEY.pub
RUN curl -fsSL https://repo.saltproject.io/py3/redhat/7/x86_64/3004.repo | tee /etc/yum.repos.d/salt.repo
RUN yum install -y salt-master

# do python libs installation
RUN python3 -m pip install pip setuptools wheel --upgrade
RUN python3 -m pip install salt-nornir[prodmin] pytest --ignore-installed PyYAML

# run Salt Nornir libs installation from local files 
COPY salt_nornir/ /tmp/salt_nornir/
COPY nornir_salt/ /tmp/nornir_salt/
RUN python3 -m pip install /tmp/nornir_salt/ --upgrade --ignore-installed PyYAML
RUN python3 -m pip install /tmp/salt_nornir/ --upgrade --ignore-installed PyYAML

ENTRYPOINT ["salt-master", "-l", "debug"]