FROM python:3.9-slim-bullseye

RUN apt-get update && \
    apt-get install -y openssh-client openssh-server curl --no-install-recommends && \
    mkdir /etc/apt/keyrings && \
    curl -fsSL -o /etc/apt/keyrings/salt-archive-keyring.gpg https://repo.saltproject.io/salt/py3/debian/11/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring.gpg arch=amd64] https://repo.saltproject.io/salt/py3/debian/11/amd64/3006 bullseye main" | tee /etc/apt/sources.list.d/salt.list && \
    apt-get update && \
    apt-get install -y salt-minion && \
    apt-get clean 
    
COPY salt_nornir/ /tmp/salt_nornir/
COPY nornir_salt/ /tmp/nornir_salt/

RUN salt-pip install --no-cache-dir /tmp/nornir_salt/.[prodmaxminion] --upgrade && \
    salt-pip install --no-cache-dir /tmp/salt_nornir/.[prodmaxminion] --upgrade

ENTRYPOINT salt-proxy --proxyid=$PROXY_ID -l trace